version: '3.4'

services:
  github:
    image: ${DOCKER_REGISTRY-}github
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Development, Staging, Production